{{- if  .Values.airflow.enabled }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name}}
    meta.helm.sh/release-namespace: {{ .Release.Namespace}}
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app.kubernetes.io/managed-by: Helm
    component: webserver
    heritage: Helm
    release: {{ .Release.Name}}
    tier: airflow
  name: {{ .Release.Name}}-airflow-webserver
  namespace: {{ .Release.Namespace}}
spec:
  ports:
  - name: airflow-ui
    nodePort: 30008 
    port: {{ .Values.airflow.ports.airflowUI}}
    protocol: TCP
    targetPort: {{ .Values.airflow.ports.airflowUI}}
  selector: 
    component: webserver
    release: {{ .Release.Name}}
    tier: airflow
  sessionAffinity: None
  type: NodePort
{{end}}